baseURL = "/"
languageCode = "it-IT"
title = "Ondazen" 
theme = "detox"
paginate = 5
#canonifyurls = true

#disqusShortname = "detox"
#googleAnalytics = "UA-109790085-1"
#relativeurls = true
#pluralizelisttitles = false

[params]
        name = "Ondazen <Parole e note>"
        description = "Parole e note"
        #copyright = "MIT"
        prod_baseurl = "http://ondazen.net"
        metadescription = "Parole e note"

[permalinks]
        post = "/:year/:month/:day/:slug"

#[params.facebook]
#  facebook = "" 
#[params.youtube]
#  youtube = "channel/UCorUTLXDYPYMQgOoqwBFlFw/" 
