+++
title = "τα ερωτικά (le cose dell'amore)"
description = "τα ερωτικά (le cose dell'amore)"
tags = [ "filosofia", "Socrate", "Platone" ]
date = "2018-10-01"
location = ""
categories = [
  "",
  ""
]
slug = ""
type = "post"
+++

“Perché gli amanti amano trascorrere tanto tempo insieme?” si domanda Platone nel Simposio. La sua risposta è che, al di là dell’attrazione sessuale, gli amanti hanno bisogno di molto tempo per poter dire cose che altrimenti non riuscirebbero a dire. Se poi ci si domanda perché mai non le riescano a dire, la risposta è che le cose dell’amore, in quanto sfuggono alle regole della ragione, sono cose indicibili. Chi ha conosciuto il sentimento dell’amore, ha certamente fatto esperienza di quello stato di grazia, che porta a dire cose che, prima di quell’incontro, non avrebbe mai osato dire nemmeno a se stesso. Quando si ama, infatti, emergono parole nuove, sconosciute persino a chi le pronuncia e in quanto tali, mai espresse prima di quel momento. Non a caso il linguaggio degli amanti spesso ci appare come un linguaggio privo di senso.  Espressioni come ”Senza di te mi casca il mondo” oppure “Non sono nulla senza di te” sono proprie di chi nell’amore è caduto e si trova dunque a vivere una situazione irripetibile nella sua unicità.

La dimensione dell’amore si colloca nella follia che, in quanto dimensione propria degli dei, è antecedente alla ragione. Per Platone Amore è ermeneuta, in quanto è il solo capace di riempire quel vuoto immenso che è fra gli uomini e gli dei, essendo il solo in grado di interpretare le parole degli dei per farle intendere agli uomini e, al tempo stesso, di tradurre le parole degli uomini per farle intendere agli dei.

 Amore è anche epistéme. Lo riconosceva lo stesso Socrate, il filosofo che più di ogni altro sa di non sapere e che della sua dotta ignoranza ha saputo fare il cardine del principio di ogni ricerca filosofica.  L’unica cosa di cui ho conoscenza, dirà Socrate, riguarda tà erotikà, cui tuttavia non è attraverso la ragione che è possibile giungere.  Egli dichiara di avere appreso delle cose dell’amore grazie ad una donna di nome Diotima. Alla donna infatti e non all’uomo, è dato accedere al grande oceano dell’irrazionale, di cui la ragione non è che una piccola isola.  Diòtima racconta a Socrate della nascita di Eros, in seguito ad un incontro avvenuto ad un banchetto in onore di Afrodite, dove un uomo ricco di nome Poros si unisce a una donna povera di nome Penia, alla quale del pranzo giungono solo briciole. Poros è in cerca di una via d’uscita da se stesso e la trova nell’incontro con la povertà, ossia con quello stato di carenza che farà di lui un desiderante. Amore e desiderio hanno infatti la stessa natura, condividendo entrambi, come loro dato costitutivo, la mancanza. Persino l’intensità stessa dell’amore è misurata dalla mancanza e in questo dato risiede la tragicità della visione greca: noi esseri umani siamo capaci di amare solo se e fino a quando l’altro ci sfugge, ossia non è in nostro possesso. Ecco perché non è affatto vero che in amore bisogna dirsi tutto, ecco perché in amore vince chi fugge.

 Da dove nasce questo stretto legame tra amore e follia? Perché abbandonarsi all’amore è così difficile? L’esperienza ci porta a dire che l’uomo ha, al tempo stesso, paura e desiderio dell’amore. A ben vedere, ciò di cui abbiamo paura non è l’amore; ciò che ci spaventa veramente è la perdita del controllo determinata dall’incontro inaspettato con quella follia che pure ci abita e ci caratterizza e che porta, ben oltre la ragione, a distinguerci gli uni dagli altri.  Tuttavia l’incontro con la nostra follia solo l’amore potrà renderlo possibile. Solo gli amanti, infatti, sono capaci di accompagnarsi reciprocamente verso l’ignoto, di procedere insieme verso quella dimensione, certamente temibile e inquietante ma, al tempo stesso, viva, potente e creativa. Perché solo l’amore, che guida e accompagna, può vincere la paura di chi è chiamato a perdersi per ritrovarsi, a uscire da sé per trovare l’estasi, a morire nel proprio ego per trovare la vera vita. Così come Dante ebbe bisogno di Virgilio per scendere agli inferi, allo stesso modo ogni amante ha bisogno dell’incontro fiducioso per entrare nella sua follia. Ecco perché non può esserci alcun rapporto tra la ragione e la follia, se non attraverso la necessaria mediazione erotica dell’altro.
